version: 2

jobs:
  test:
    docker:
      - image: michaelth/node-chrome
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - node_modules-

      - run: 
          name: install node packages
          command: npm install

      - run:
          name: Running tests
          command: npm test --headless

      - run:
          name: Running eslint standard style
          command: npm run eslint

      - save_cache:
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  publish:
    working_directory: ~/repo
    docker:
      - image: michaelth/node-chrome
    steps:
      - checkout
      - run:
          name: Publish to npm
          command: scripts/publish.sh

workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
